// src/popup/components/SiteCard.tsx
import React from 'react';
import { SITE_STATUS } from '../../shared/constants';
import { EnhancedSite } from '../../shared/stores/siteStore';

interface SiteCardProps {
  site: EnhancedSite;
  onFocusTab: (siteId: string) => void;
}

export function SiteCard({ site, onFocusTab }: SiteCardProps) {
  const handleCardClick = () => {
    // Focus the site tab if enabled (regardless of connection status)
    if (site.enabled) {
      onFocusTab(site.id);
    }
  };

  const cursorStyle = site.enabled ? 'cursor-pointer' : 'cursor-default';

  return (
    <div
      className={`site-card bg-ai-bg-card border border-ai-border rounded-lg p-3 h-12 transition-all ${cursorStyle}`}
      onClick={handleCardClick}
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <div
            className="w-4 h-4 rounded-full site-logo"
            style={{ backgroundColor: site.color }}
          ></div>
          <span className="text-sm font-medium text-ai-text-primary">{site.name}</span>
        </div>
        <div className={`w-2 h-2 rounded-full flex-shrink-0 ${site.status === SITE_STATUS.CONNECTED ? 'bg-ai-success' : site.status === SITE_STATUS.LOADING ? 'bg-ai-warning' : 'bg-ai-text-disabled'}`}></div>
      </div>
    </div>
  );
}

// src/entrypoints/sidepanel/components/Compose/SitesSection/SiteCard.svelte
<script lang="ts">
  import { SITE_STATUS } from '@/shared';
  import type { EnhancedSite } from '@/types';
  import { tabOperationsActions } from '../../../stores/tabOperationsStore';
  import { siteActions } from '../../../stores/siteStore';
  import { toastActions } from '../../../stores/toastStore';

  interface Props {
    site: EnhancedSite;
  }

  let { site }: Props = $props();

  function handleCardClick(event: MouseEvent) {
    // Don't trigger if clicking on the toggle
    const target = event.target as HTMLElement;
    if (target.type === 'checkbox' || target.closest('label')) {
      return;
    }

    // Focus the site tab if enabled
    if (site.enabled) {
      tabOperationsActions.focusTab(site.id, site.name);
    }
  }

  async function handleToggle(event: Event) {
    const target = event.target as HTMLInputElement;
    await siteActions.toggleSite(site.id, target.checked);
    toastActions.showToast(
      `${target.checked ? 'Enabled' : 'Disabled'} ${site.name}`,
      'info',
    );
  }

  const cursorStyle = $derived(
    site.enabled ? 'cursor-pointer' : 'cursor-default',
  );
  const statusColor = $derived(
    site.status === SITE_STATUS.CONNECTED
      ? 'pc-status-connected'
      : site.status === SITE_STATUS.LOADING
        ? 'pc-status-loading'
        : site.status === SITE_STATUS.ERROR
          ? 'pc-status-error'
          : 'pc-status-disconnected',
  );
</script>

<div
  class="pc-card p-3 h-14 pc-transition {cursorStyle}"
  onclick={handleCardClick}
  onkeypress={(e) => e.key === 'Enter' && handleCardClick(e)}
  role="button"
  tabindex="0"
  style="opacity: {site.enabled ? '1' : '0.6'};"
>
  <div class="flex items-center justify-between h-full">
    <div class="flex items-center space-x-3 min-w-0 flex-1">
      <div
        class="w-4 h-4 rounded-full site-logo flex-shrink-0"
        style="background-color: {site.color};"
      ></div>
      <span class="text-sm font-medium pc-text-primary truncate">{site.name}</span>
      <div class="w-2 h-2 rounded-full flex-shrink-0 {statusColor}"></div>
    </div>

    <label
      class="relative inline-flex items-center cursor-pointer flex-shrink-0 ml-3"
      id="site-toggle-{site.id}"
      onclick={(e) => e.stopPropagation()}
    >
      <input
        type="checkbox"
        class="sr-only peer"
        checked={site.enabled}
        id="site-checkbox-{site.id}"
        onchange={handleToggle}
      />
      <div
        class="w-11 h-6 rounded-full peer-focus:outline-none peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:rounded-full after:h-5 after:w-5 after:transition-all"
        style="background-color: {site.enabled
          ? 'var(--pc-success)'
          : 'var(--pc-border)'};"
      ></div>
    </label>
  </div>
</div>

<style>
  .pc-card:hover {
    background-color: var(--pc-bg-hover);
  }

  label:hover {
    transform: scale(1.05);
  }

  .peer:checked + div::after {
    background-color: var(--pc-text-inverted);
  }

  .peer + div::after {
    background-color: var(--pc-text-primary);
  }
</style>
