// src/entrypoints/popup/components/Settings/Settings.svelte
<script lang="ts">
  import ThemeSelector from './ThemeSelector.svelte';
  import type { EnhancedSite, ThemeOption } from '@/types';
  import {
    sitesWithStatus,
    siteActions,
    isLoadingSites,
  } from '../../stores/siteStore';
  import {
    theme,
    resolvedTheme,
    themeOptions,
    themeActions,
  } from '../../stores/themeStore';
  import { toastActions } from '../../stores/toastStore';

  // Get reactive store values
  let sites = $derived.by(() => {
    const sitesWithStatusFn = $sitesWithStatus as (
      isDark?: boolean,
    ) => Record<string, EnhancedSite>;
    const isDark = $resolvedTheme === 'dark';
    return sitesWithStatusFn(isDark);
  });

  let currentTheme = $derived($theme as ThemeOption);
  let availableThemeOptions = $derived(themeOptions);

  let siteValues = $derived(Object.values(sites));

  // Handle site toggle
  function handleSiteToggle(siteId: string, enabled: boolean) {
    siteActions.toggleSite(siteId, enabled);
    toastActions.showToast(
      `${enabled ? 'Enabled' : 'Disabled'} ${sites[siteId]?.name}`,
      'info',
    );
  }
</script>

<div class="space-y-4">
  <!-- Site Settings -->
  <section class="space-y-2">
    <header class="flex items-center justify-between">
      <h3 class="text-sm font-medium pc-text-primary">Sites</h3>
      <div class="w-6 h-6"></div>
    </header>

    <div class="space-y-2">
      {#if $isLoadingSites}
        <div class="flex items-center justify-center p-4">
          <div class="text-sm pc-text-secondary">Loading sites...</div>
        </div>
      {:else}
        {#each siteValues as site (site.id)}
          <article
            class="flex items-center justify-between p-3 h-12 rounded-lg pc-card"
          >
            <div class="flex items-center space-x-2">
              <div
                class="w-4 h-4 rounded-full"
                style="background-color: {site.color};"
              ></div>
              <span class="text-sm font-medium pc-text-primary"
                >{site.name}</span
              >
            </div>

            <label
              class="relative inline-flex items-center cursor-pointer flex-shrink-0"
            >
              <input
                type="checkbox"
                class="sr-only peer"
                checked={site.enabled}
                onchange={(e) => {
                  const target = e.target as HTMLInputElement;
                  handleSiteToggle(site.id, target.checked);
                }}
              />
              <div
                class="w-11 h-6 rounded-full peer-focus:outline-none peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:rounded-full after:h-5 after:w-5 after:transition-all"
                style="background-color: {site.enabled
                  ? 'var(--pc-success)'
                  : 'var(--pc-border)'}; --after-bg: {site.enabled
                  ? 'var(--pc-text-inverted)'
                  : 'var(--pc-text-primary)'};"
              ></div>
            </label>
          </article>
        {/each}
      {/if}
    </div>
  </section>

  <!-- Theme Settings -->
  <section>
    <ThemeSelector
      {currentTheme}
      themeOptions={availableThemeOptions}
      onThemeChange={themeActions.setTheme}
    />
  </section>
</div>

<style>
  .peer:checked + div::after {
    background-color: var(--after-bg);
  }

  .peer + div::after {
    background-color: var(--after-bg);
  }
</style>

// src/popup/components/Settings.tsx
import React from 'react';
import { ThemeOption } from '../../shared/constants';
import { EnhancedSite } from '../../types';
import { ThemeSelector } from './ThemeSelector';

interface ThemeOptionItem {
  value: ThemeOption;
  label: string;
}

interface SettingsProps {
  sites: Record<string, EnhancedSite>;
  onSiteToggle: (siteId: string, enabled: boolean) => void;
  currentTheme: ThemeOption;
  themeOptions: ThemeOptionItem[];
  onThemeChange: (theme: ThemeOption) => void;
}

export function Settings({ sites, onSiteToggle, currentTheme, themeOptions, onThemeChange }: SettingsProps) {
  return (
    <>
      {/* Site Settings */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-medium text-ai-text-primary">Sites</h3>
          <div className="w-6 h-6"></div>
        </div>

        <div className="space-y-2">
          {(Object.values(sites)).map((site) => (
            <div
              key={site.id}
              className="flex items-center justify-between p-3 h-12 bg-ai-bg-card border border-ai-border rounded-lg"
            >
              <div className="flex items-center space-x-2">
                <div
                  className="w-4 h-4 rounded-full"
                  style={{ backgroundColor: site.color }}
                ></div>
                <span className="text-sm font-medium text-ai-text-primary">{site.name}</span>
              </div>

              <label className="relative inline-flex items-center cursor-pointer flex-shrink-0">
                <input
                  type="checkbox"
                  className="sr-only peer"
                  checked={site.enabled}
                  onChange={(e) => onSiteToggle(site.id, e.target.checked)}
                />
                <div className="w-11 h-6 bg-ai-border peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-ai-text-inverted after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-ai-text-primary after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-ai-success"></div>
              </label>
            </div>
          ))}
        </div>
      </div>

      {/* Theme Settings */}
      <ThemeSelector
        currentTheme={currentTheme}
        themeOptions={themeOptions}
        onThemeChange={onThemeChange}
      />
    </>
  );
}
