// src/entrypoints/popup/components/Compose/SitesSection/SiteCard.svelte
<script lang="ts">
  import { SITE_STATUS } from '@/shared';
  import type { EnhancedSite } from '@/types';
  import { tabOperationsActions } from '../../../stores/tabOperationsStore';

  interface Props {
    site: EnhancedSite;
  }

  let { site }: Props = $props();

  function handleCardClick() {
    // Focus the site tab if enabled (regardless of connection status)
    if (site.enabled) {
      tabOperationsActions.focusTab(site.id, site.name);
    }
  }

  const cursorStyle = $derived(
    site.enabled ? 'cursor-pointer' : 'cursor-default',
  );
  const statusColor = $derived(
    site.status === SITE_STATUS.CONNECTED
      ? 'pc-status-connected'
      : site.status === SITE_STATUS.LOADING
        ? 'pc-status-loading'
        : site.status === SITE_STATUS.ERROR
          ? 'pc-status-error'
          : 'pc-status-disconnected',
  );
</script>

<div
  class="pc-card p-3 h-12 pc-transition {cursorStyle}"
  onclick={handleCardClick}
  onkeypress={(e) => e.key === 'Enter' && handleCardClick()}
  role="button"
  tabindex="0"
>
  <div class="flex items-center justify-between">
    <div class="flex items-center space-x-2">
      <div
        class="w-4 h-4 rounded-full site-logo"
        style="background-color: {site.color};"
      ></div>
      <span class="text-sm font-medium pc-text-primary">{site.name}</span>
    </div>
    <div class="w-2 h-2 rounded-full flex-shrink-0 {statusColor}"></div>
  </div>
</div>

<style>
  .pc-card:hover {
    transform: translateY(-1px);
    box-shadow: var(--pc-shadow-md);
  }
</style>

// src/popup/components/SiteCard.tsx
import React from 'react';
import { SITE_STATUS } from '../../shared/constants';
import { EnhancedSite } from '../../types';

interface SiteCardProps {
  site: EnhancedSite;
  onFocusTab: (siteId: string) => void;
}

export function SiteCard({ site, onFocusTab }: SiteCardProps) {
  const handleCardClick = () => {
    // Focus the site tab if enabled (regardless of connection status)
    if (site.enabled) {
      onFocusTab(site.id);
    }
  };

  const cursorStyle = site.enabled ? 'cursor-pointer' : 'cursor-default';

  return (
    <div
      className={`site-card bg-ai-bg-card border border-ai-border rounded-lg p-3 h-12 transition-all ${cursorStyle}`}
      onClick={handleCardClick}
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <div
            className="w-4 h-4 rounded-full site-logo"
            style={{ backgroundColor: site.color }}
          ></div>
          <span className="text-sm font-medium text-ai-text-primary">{site.name}</span>
        </div>
        <div className={`w-2 h-2 rounded-full flex-shrink-0 ${site.status === SITE_STATUS.CONNECTED ? 'bg-ai-success' : site.status === SITE_STATUS.LOADING ? 'bg-ai-warning' : 'bg-ai-text-disabled'}`}></div>
      </div>
    </div>
  );
}
